# Generated by Django 5.2.12 on 2026-03-26 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("abbreviation", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=100)),
                ("franchise_id", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=100)),
                ("sweater_number", models.CharField(blank=True, max_length=10)),
                ("position", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("headshot_url", models.URLField(blank=True, max_length=500)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "current_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="nhl.team",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("season", models.CharField(db_index=True, max_length=20)),
                ("game_type", models.PositiveSmallIntegerField(default=2)),
                ("date", models.DateTimeField(db_index=True)),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="scheduled", max_length=50)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="nhl.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="nhl.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GoalieSeasonStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("season", models.CharField(db_index=True, max_length=20)),
                ("games_played", models.PositiveSmallIntegerField(default=0)),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("save_pct", models.FloatField(blank=True, null=True)),
                ("gaa", models.FloatField(blank=True, null=True)),
                ("shutouts", models.PositiveSmallIntegerField(default=0)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goalie_stats",
                        to="nhl.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "-wins"],
                "unique_together": {("player", "season")},
            },
        ),
        migrations.CreateModel(
            name="SkaterSeasonStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("season", models.CharField(db_index=True, max_length=20)),
                ("games_played", models.PositiveSmallIntegerField(default=0)),
                ("goals", models.PositiveSmallIntegerField(default=0)),
                ("assists", models.PositiveSmallIntegerField(default=0)),
                ("points", models.PositiveSmallIntegerField(default=0)),
                ("plus_minus", models.SmallIntegerField(default=0)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skater_stats",
                        to="nhl.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "-points"],
                "unique_together": {("player", "season")},
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("games_played", models.PositiveSmallIntegerField(default=0)),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("ot_losses", models.PositiveSmallIntegerField(default=0)),
                ("points", models.PositiveSmallIntegerField(default=0)),
                ("point_pct", models.FloatField(blank=True, null=True)),
                ("division_name", models.CharField(blank=True, max_length=100)),
                ("conference_name", models.CharField(blank=True, max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="nhl.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-points"],
                "unique_together": {("team", "date")},
            },
        ),
    ]
